# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 508eb074c9f6eb136786cf5392c9d62be535b79b9bd5e0753d4129ea79e0e235270c8f1b7a6318d90c9232d60855651cfd4f83fdb5d02561e9e54c86420edb22

test:
  secret_key_base: f0bf3887855eb448671048dcad6ea7d319921ded77a00d6781d3641a7c3386c9e44c50c7807dbd78817e28e8de76b5f71d32b964a43bc07d2dcc3bdae45119dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
